name: DataOps CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    # Definição das variáveis globais do pipeline do GitHub
    env:
      DATABRICKS_ENVIRONMENT: staging  # O CI testará simulando o ambiente de Staging    

    steps:
    # Baixa o código do seu repositório para a máquina virtual do GitHub
    - name: Checkout Code
      uses: actions/checkout@v4

    # Instala o Java (Obrigatório para o Apache Spark rodar nos bastidores)
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    # Configura o Python na máquina virtual
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # Instala as dependências PySpark e PyTest
    - name: Install Dependencies
      run: |
        python -m pip upgrade pip
        pip install pyspark pytest faker

    # Executa os testes automatizados de Engenharia de Dados
    - name: Run Data Quality Tests
      run: |
        continue-on-error: true # mudar para false quando em prod
        pytest tests/